name: Matrix demo
on:
  push:
    branches:
      - master
jobs:
  continue-on-error: true
  strategy:
    matrix:
      node-version: [12,14,16]
      operating-system: [ubuntu-latest, windows-latest]
  build:
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependices
        run: npm ci
      - name: Build project
        run: npm run build
